#!/usr/bin/perl

# biocode_add_tissue
# Joyce Gross - Feb 25, 2006


# $DEBUG=1;

require "utils.p";
require "myquery_utils.p";
require "myschema.p";
require "mybiocode_utils.p";
require "biocode_settings";

## uncomment for system crashes
#$CRASH = 1;  ## queries will just exit out of readParse
#$crash_date = "Tue Apr 21 18:30:54 PDT 2009";


$help_win_link = "<a href=\"javascript:Help_Window('/cgi/biocode_help?page";

# get DateFirstEntered
$input{DateFirstEntered} = $TODAY;
$its_an_update = 0;
$its_a_delete = 0;

&readParse(*input) || print "    <p>No input data processed.<p>\n";


####
# new record vs. update
####
if  ($input{'mode'} eq "update") {
    $its_an_update = 1;
    $heading = "Moorea Biocode: Update a Tissue Record";
    $form_bg_color = $lt_sage_color;
} elsif  ($input{'mode'} eq "delete") {
    $its_a_delete = 1;
    $heading = "Moorea Biocode: Delete a Tissue Record";
    $form_bg_color = $lt_sage_color;
} else {
    $heading = "Moorea Biocode: Add a New Tissue Record";
    $form_bg_color = $lt_bluegray_color;
}

#####
# step 2 ready to load it - check input
#####
if ($input{'special'} eq "load") {
    &check_input;
    if ($bad_msg) {
        &print_biocode_form_header($heading, $form_bg_color);
        &print_form;
        &print_biocode_form_footer;
        exit;

    } elsif ($input{'mode'} eq "update") {
        &update_record;
        &send_email;
        &print_biocode_form_header($heading, $form_bg_color);
        print "<b>Tissue \# $input{bnhm_id}.$input{tissue_num} was successfully updated</b>\n";
        print "<br>\n";
        print "<a target=new ";
        print "href=/cgi/biocode_tissue_query?bnhm_id=$input{bnhm_id}";
        print "&tissue_num=$input{tissue_num}";
        print "&one=T>click here to view this record</a> &nbsp;&nbsp;\n";
        print "<a target=new ";      # JG added for biocode
        print "href=/cgi/biocode_add_tissue?bnhm_id=$input{bnhm_id}&table=biocode>";
        print "add a tissue record for this specimen</a> &nbsp;&nbsp;\n";
#        print "<a target=new ";      # JG added for biocode
#        print "href=/cgi/biocode_add_photo?bnhm_id=$input{bnhm_id}&table=biocode>";
#        print "add a photo of this specimen</a> \n";

        ## need firstscreen?
        print "<FORM name=parentform ACTION=\"/cgi/biocode_add_tissue\" METHOD=\"post\">";
        print "<p>Update another record: <INPUT type=hidden name=mode value=update>";
        print "<INPUT type=hidden name=entry_by value=\"$input{entry_by}\">";
        print "<INPUT name=bnhm_id> <INPUT TYPE=\"submit\" VALUE=\"Go\">";
        print "</form>";
        &print_biocode_form_footer;
        exit;

    } else {
        $old_tissue_num = $input{tissue_num};
        #$input{tissue_num} = &get_next_tissue_num;
        #$tissue_num = $input{tissue_num};
        ($input{seq_num}) = &get_one_record("select uuid()");   # added 8/14/2008 JG 
        &load_record;
        &send_email;
        &print_biocode_form_header($heading, $form_bg_color);
        print "<center><p>";
        print "<b><small>Tissue ID \# $input{bnhm_id}.$old_tissue_num was loaded successfully</b>\n";
        print "<a target=new ";
        print "href=/cgi/biocode_tissue_query?bnhm_id=$input{bnhm_id}&tissue_num=$old_tissue_num&one=T>";
        print "view this tissue record</a></small> &nbsp;&nbsp;\n";

#        print "<small><a target=new ";      # JG added for biocode
#        print "href=/cgi/biocode_add_photo?bnhm_id=$input{bnhm_id}&table=biocode>";
#        print "add a photo of this specimen</a></small> \n";
        &print_clear_form_button;
        print "</center>";
        # print $loadfile_for_debug;
        print "<hr>\n";
        &print_form;
        &print_biocode_form_footer;
    }
    exit;

} elsif($input{mode} eq "delete") {

    if($input{special} eq "final") {
        &print_biocode_form_header($heading, $form_bg_color);
        &delete_tissue_record;
        &print_delete_tissue_form_done;
	&send_email;
	exit;
    } else {
        &print_biocode_form_header($heading, $form_bg_color);
        &print_delete_tissue_form;
	exit;
    }

#####
# step 1 print the form (if nec, first check password)
#####
} else {
    $fresh_record = 1;  # for some initial values

    if ($input{'special'} eq "firstscreen") {  ## check the password

	if ($its_an_update) {
	    $cat_id_OK = &check_incoming_cat_id($input{bnhm_id},"tissue");
	    $tissue_num = $input{tissue_num};
	}
	$passwd_OK = &check_biocode_name_and_password($input{entry_by},$input{password});
	
	if (!$passwd_OK || ($its_an_update && !$cat_id_OK)) {
	    &print_biocode_err_and_exit;
	} else {
	    &print_biocode_form_header($heading, $form_bg_color);
	    &print_form;
	    &print_biocode_form_footer;
	    exit;
	}

    } elsif ($its_an_update) {  # second or later update - password already OK
	$cat_id_OK = &check_incoming_cat_id($input{bnhm_id},"tissue");
	&print_biocode_form_header($heading, $form_bg_color);
        &print_form;
        &print_biocode_form_footer;
        exit;

    } else {   # don't need a password
        &print_biocode_form_header($heading, $form_bg_color);
        &print_form;
        &print_biocode_form_footer;
        exit;
    }
}



sub print_form {

    if ($its_an_update) {
	if ($bad_msg) {  ## need to re-set the values
	    foreach $v (@biocode_tissue_schema) {
		${$v} = $input{$v};
	    }   
        } else {
            $select = "select * from biocode_tissue where bnhm_id = '$input{bnhm_id}' and tissue_num = '$input{tissue_num}'";
            # print "<p>HI<p>";
            # print "<p>select: $select<p>";
            @row = &get_one_record($select, "biocode");
            &fill_fields_with_values("biocode_tissue");
            # $input{batch_id} = $batch_id;
        }

    } else {
	### Get values that were entered into form, to re-print them.
	foreach $v (@biocode_tissue_schema) {
	    ${$v} = $input{$v};
	# DEBUG # print "$v: $input{$v} ...";
        }
    }
    if ($bad_msg) {
	print "<font color=red><b>";
	print "Errors found - please correct and submit again...</b></font>\n";
        print "<small>Problems? email <a href=mailto:bscit\@berkeley.edu?subject=biocode_add_tissue>bscit\@berkeley.edu</a></small>";
	&print_clear_form_button;
	print "<small>$bad_msg</small>\n";
	print "<hr>\n";
        if($input{mode} eq "delete" || $input{mode} eq "update") {
            exit;
        }

    } elsif ($input{carryforward}) {
	$carryforward = $input{carryforward};
        $tissue_num = &get_next_tissue_num;
        $bad_msg .= "<li>Carryforward tissue_num = $tissue_num";

    } elsif ($fresh_record) {
	if ($its_an_update) {
	    ## use stuff from the record
	} else {
	    ## get some initial values
	    $bnhm_id = $input{bnhm_id};

	    $record_exists = &check_for_specimen_record($bnhm_id);
            if(!$record_exists) {
                $bad_msg .= "Record $bnhm_id does not exist in the Biocode specimen database.";
            } else {
		$tissue_num = &get_next_tissue_num;
		($Coll_EventID,$Specimen_Num_Collector) = &get_one_record("select Coll_EventID,Specimen_Num_Collector from biocode where bnhm_id = '$bnhm_id'","biocode");

	    }
	    # $bad_msg .= "<li>tissue_num = $tissue_num";
            if ($bad_msg) {
	        print "<font color=red><b>";
                print "Errors found - please correct and submit again...</b></font>\n";
	        print "<small>$bad_msg</small>\n";
		&print_biocode_form_footer;
                exit;
            }
        }
    } else {	## just do the usual

    }

    if($its_an_update) {
        $url_entry_by = $input{entry_by};
        $url_entry_by =~ s/ /\+/g;

        print "<center>\n";
        print "[<a href=/cgi/biocode_add_tissue?bnhm_id=$input{bnhm_id}&tissue_num=$input{tissue_num}&entry_by=$url_entry_by&mode=delete>delete this tissue record</a>: $input{bnhm_id}.$input{tissue_num}]<p>";
        print "<center>\n";
        # print "<input type=hidden name=batch_id value=\"$input{batch_id}\">";
    }
    print "<form name=parentform action=/cgi/biocode_add_tissue method=post>\n";
    print "<center>\n";
    print "<table>\n";
    print "<tr>\n";

    &print_column_1;
    &print_column_2;

    print "</tr>\n";
    print "</table>\n";
    print "</form>\n";
}

sub print_column_1 {

    print "<td align=left valign=top>\n";

    ## print bnhm_id and tissue_num

    if (!$tissue_num) {
	$tissue_num = $input{tissue_num};  # didn't get set by get_next_tissue_num
    }
    if (!$bnhm_id) {
        $bnhm_id = $input{bnhm_id};  # must be an update
    }


    print "<table cellspacing=5 cellpadding=5>\n";

    print "<tr>\n";
    print "<td align=right>\n";
    print "<input type=hidden name=bnhm_id value=\"$bnhm_id\">\n";
    print "$help_win_link=CatID')\">Biocode ID Num";
    print "<td>";
    print "$input{bnhm_id}";
    print "<input type=hidden name=tissue_num value=$tissue_num>\n";
    print "&nbsp;&nbsp;.$tissue_num";
    print "</td>\n";
    print "</tr>\n";

#    print "<tr>\n";
#    print "<td align=right>$help_win_link=Specimen_Num_Collector')\">Specimen No.</a></td>\n";
#    print "<td align=left>";
#    print "<input size=20 name=Specimen_Num_Collector value=\"$Specimen_Num_Collector\"";
#    if ($Specimen_Num_Collector)  { print " class=yellbg"; }
#    print ">\n";
#    print "</td>\n";
#    print "</tr>\n";

    &print_collector_info;
    print "</td>\n";
}



sub print_column_2 {
    ### Column Two ###
    print "<td align=left valign=top>\n";
    print "<table>\n";

    print "<tr>\n";
    print "<td align=right>$help_win_link=Container')\">Container</a></td>\n";
    print "<td>";
    print "<select size=1 name=container ";
    if ($container)  { print " class=yellbg"; }
    print ">\n";
    &print_container_options($container);
    print "</select>\n";
    &print_add_a_new_container_button($input{entry_by},1); # mybiocode_utils.p
    print "</td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td align=right>$help_win_link=preservative')\">Preservative</a></td>\n";
    print "<td>";
    print "<select size=1 name=preservative ";
    if ($preservative)  { print " class=yellbg"; }
    print ">\n";
    &print_preservative_options($preservative);
    print "</select>\n";
    &print_add_a_new_preservative_button($input{entry_by},1); # mybiocode_utils.p
    print "</td>\n";
    print "</tr>\n";

    # 6/25/08 GO eliminated picklist
    print "<tr>\n";
    print "<td align=right>$help_win_link=TissueType')\">Tissue Type</a></td>\n";
    print "<td align=left>";
    print "<input size=20 name=tissuetype value=\"$tissuetype\"";
    if ($tissuetype)  { print " class=yellbg"; }
    print ">\n";
    print "</td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td align=right>$help_win_link=molecular_id')\">Molecular ID</a></td>\n";
    print "<td align=left>";
    print "<input size=20 name=molecular_id value=\"$molecular_id\"";
    if ($molecular_id)  { print " class=yellbg"; }
    print ">\n";
    print "</td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td align=right>$help_win_link=format_name96')\">96 Format Name</a></td>\n";
    print "<td align=left>";
    print "<input size=20 name=format_name96 value=\"$format_name96\"";
    if ($format_name96)  { print " class=yellbg"; }
    print ">\n";
    print "</td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td align=right>$help_win_link=well_number96')\">96 Well Number</a></td>\n";
    print "<td align=left>";
    print "<input size=20 name=well_number96 value=\"$well_number96\"";
    if ($well_number96)  { print " class=yellbg"; }
    print ">\n";
    print "</td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td align=right>$help_win_link=Notes')\">Notes</a></td>\n";
    print "<td align=left>";
    print "<textarea wrap=hard name=notes cols=15 rows=2";
    if ($notes)  { print " class=yellbg"; }
    print ">$notes</textarea>\n";
    print "</td>\n";
    print "</tr>\n";


    print "</table>\n";

    ### End of Column Two ###

    # print "<br>\n";

    print "<input type=hidden name=special value=load>\n";
    print "<input type=hidden name=carryforward value=1>\n";

    print "<input type=hidden name=entry_by value = \"$input{entry_by}\" >\n";
    if ($its_an_update) {
	print "<input type=hidden name=mode value=update>\n";
	print "<input type=submit value=\"Update Tissue Record\">\n";
    } else {
	print "<input type=submit value=\"Submit New Tissue Record\">\n";
    }
    print "</td>\n";
}

sub print_collector_info {


    &print_one_subsampler_option;  # mybiocode_utils.p

    print "<tr>\n";
    print "<td align=left colspan=2>$help_win_link=HoldingInstitution')\">Institution";
    print "</a><font color=red> * </font>\n";

    print "<select size=1 name=HoldingInstitution ";
    if($HoldingInstitution) { print "class=yellbg "; }
    print ">";
    &print_holding_institution_options($HoldingInstitution);
    print "</select>";

    print "</td>\n";
    print "</tr>\n";



    print "<tr>\n";
    print "<td align=right>$help_win_link=OtherCatalogNum')\">Other Catalog Number</a></td>\n";
    print "<td align=left>";
    print "<input size=20 name=OtherCatalogNum value=\"$OtherCatalogNum\"";
    if ($OtherCatalogNum)  { print " class=yellbg"; }
    print ">\n";
    print "</td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td align=right>$help_win_link=from_tissue')\">Subsampling Source</a></td>\n";
    print "<td align=left>";
    print "<input size=20 name=from_tissue value=\"$from_tissue\"";
    if ($from_tissue)  { print " class=yellbg"; }
    print ">\n";
    print "</td>\n";
    print "</tr>\n";


    print "<tr>\n";
    print "<td align=right>$help_win_link=CollectionDate')\">Date Taken";
    print "</a>\n";
    print "<font color=red> * </font>\n";
    print "</td>\n";
    print "<td align=left><nobr>\n";
    print "<input size=4 maxlength=4 name=year value=$year";
    if ($year) { print " class=yellbg"; }
    print ">yyyy\n";
    print "<input size=2 maxlength=2 name=month value=$month";
    if ($month) { print " class=yellbg"; }
    print ">mm\n";
    print "<input size=2 maxlength=2 name=day value=$day";
    if ($day) { print " class=yellbg"; }
    print ">dd\n";
    print "</nobr></td>\n";
    print "</tr>\n";

    
    print "</table>\n";

    print "<table>\n";


    print "<tr>\n";
    print "<td colspan=2><p><br>";
    print "<font color=red> * Required field</font>\n";
    print "</td>\n";
    print "</tr>\n";

    print "</table>\n";
}

sub check_input {

    ## change 'unselected' to ''
    foreach $s (@biocode_tissue_schema) {
        if ($input{$s} eq "unselected") {
            $input{$s} = "";
        }
    }
    ## these check incoming stuff, and also add more info
    #&check_numbers;
    &check_ymd_dates;          # mybiocode_utils.p
    &check_five_collectors;    # mybiocode_utils.p
    if ($input{from_tissue}) {  # added 6/28 GO
	&check_for_valid_tissue($input{from_tissue}); # mybiocode_utils.p
    }
    $msg = &check_well_and_plate_name_formats("$input{well_number96}","$input{format_name96}","$its_an_update");
    $bad_msg .= $msg;  # Feb 17 note: doesn't seem to do any other error checking (person, date, institution....)

    $input{well_number96} = ucfirst($input{well_number96});  # letter must be caps
} 


sub check_numbers {
    ## NOT IN USE AS OF 5/23/08 GO

    $input{seq_num} = 0;

    if (!$input{ProjectCode}) {
        $bad_msg .= "<dd><li><b>Project Code</a> is required\n";
    }
    if (!$input{CatalogNumberNumeric}) {
        $bad_msg .= "<dd><li><b>Catalog Number</b> is required";

    } elsif ($its_an_update) {
        # just create bnhm_id
        $input{bnhm_id} = $input{ProjectCode} . $input{CatalogNumberNumeric};

    } else {
        $OK = &is_an_integer($input{CatalogNumberNumeric});
        if (!$OK) {
            $bad_msg .= "<dd><li><b>Catalog Number</b> ";
            $bad_msg .= "\"$input{CatalogNumberNumeric}\" is not an integer";
	} else {
	    $input{bnhm_id} = $input{ProjectCode} . $input{CatalogNumberNumeric};
	    $CatNumExists = &get_count(biocode,"bnhm_id='$input{bnhm_id}'");
#	    if ($CatNumExists) {
#		$bad_msg .= "<dd><li><b>Collection ID</b> $input{bnhm_id} already exists &nbsp; ";
#		$bad_msg .= "<a target=new ";
#		$bad_msg .= "href=/cgi/biocode_query?where-bnhm_id=$input{bnhm_id}>";
#		$bad_msg .= "click here to see it</a>";
#	    }
	}
    }



}



sub load_record {

    $loadfile = "";
    $loadfile_for_debug = "";

    ($input{seq_num}) = &get_one_record("select uuid()");   # added 2/17/2009 JG 

    ## make load file
    foreach $attr (@biocode_tissue_schema) {
        $val = &strip($input{$attr});
        if (!$val || $val eq "unselected" || $val eq "none") {
            $val = "\\N";
        }
	    $loadfile .= "$val|";

	    # print field names in orange for debugging
	    $loadfile_for_debug .= "<font color=orange>$attr=</font>|$val| ";
    }
    &load_biocode_record($loadfile,"biocode_tissue");  # mybiocode_utils.p

    ## update biocode Tissue count (GO 5/22/08)
    $update_stmt = "update biocode set Tissue = $input{tissue_num} where bnhm_id='$input{bnhm_id}'";
    &process_query($update_stmt, "biocode");
    # debug $bad_msg = "<li>Update statement: $update_stmt";

}

sub update_record {

    # delete old record, insert new record

    #$debugging = 1;

    ## first, save old record
    $save_statement = "insert into biocode_tissue_deleted select * from biocode_tissue where bnhm_id=\"$input{bnhm_id}\" and tissue_num=$input{tissue_num}";
    &process_query($save_statement, "biocode");

    $del_statement = "delete from biocode_tissue where bnhm_id=\"$input{bnhm_id}\" and tissue_num = $input{tissue_num}";
    if ($debugging) {
        # print "$del_statement<p>";
    } else {
        &process_query($del_statement, "biocode");
	&load_record;
    }
}

sub send_email {


    if ($its_an_update) {
        open(MESSAGE, "| mailx -s \"Biocode tissue update ($input{entry_by}) \" $recipients");
        print MESSAGE "A tissue record ($input{bnhm_id}.$input{tissue_num}) ";
        print MESSAGE "has been updated in ";
        print MESSAGE "the Biocode tissue database. \n\n";
	
    } elsif ($input{mode} eq "delete") {
	open(MESSAGE, "| mailx -s \"Biocode tissue deleted ($input{entry_by}) \" $recipients");
	print MESSAGE "A tissue record ($input{bnhm_id}.$input{tissue_num}) ";
	print MESSAGE "has been deleted from ";
        print MESSAGE "the Biocode tissue database. \n\n";


    } else {
	open(MESSAGE, "| mailx -s \"Biocode new tissue record ($input{entry_by})\" $recipients");
	print MESSAGE "A new tissue record ($input{bnhm_id}.$input{tissue_num}) ";
	print MESSAGE "has been loaded into ";
	print MESSAGE "the Biocode tissue database. \n\n";
    }
    
    print MESSAGE "URL:\n";
    print MESSAGE "http://biocode.berkeley.edu/cgi/biocode_query?bnhm_id=$input{bnhm_id}&one=T&OK2SHOWPRIVATE=1\n\n";

    print MESSAGE "Load file: $loadfile\n\n";

    print MESSAGE "Weekly load file: $weeklycopy\n\n";

    close(MESSAGE);
}

sub print_clear_form_button {
    
    $url_entry_by = $input{entry_by};
    $url_entry_by =~ s/ /\+/g;
    print "&nbsp;&nbsp;&nbsp;&nbsp;";
    print "<a href=/cgi/biocode_add_tissue?entry_by=$url_entry_by>";
    print "<small>[CLEAR FORM]</small></a>\n";


    if ($Submit) {
	print "<form name=parentform method=post action=\"/cgi/biocode_add_tissue\">\n";
	print "<input type=hidden name=special value=another>\n";
	print "<input type=hidden name=entry_by value=\"$input{entry_by}\">\n";
	print "<br><input type=submit value=\"Clear Form\">\n\n";
	print "</form>\n";
    }
}

sub print_refresh_list_button {
    
    $url_entry_by = $input{entry_by};
    $url_entry_by =~ s/ /\+/g;
    print "&nbsp;&nbsp;&nbsp;&nbsp;";
    print "<a href=/cgi/biocode_add_tissue?entry_by=$url_entry_by>";
    print "[refresh list]</a>\n";

}

sub set_specimen_initial_values {

    ## NOT IN USE AS OF 5/23/08  GO

    ## get some initial values
    if($input{bnhm_id} =~ /([a-zA-Z]+)(\d+)/) {
        $ProjectCode = uc($1);
        $CatalogNumberNumeric = "$2";
    }
}

sub get_next_tissue_num {
    # get next tissue_num

    # $bad_msg .= "<li>bnhm_id: $bnhm_id\n";
    ($current_max) = &get_one_record("select max(tissue_num) from biocode_tissue where bnhm_id = '$bnhm_id'","biocode");
    # $bad_msg .= "<li>current_max = $current_max";
    if (!$current_max) {
	return 1;
    } else {
	$current_max++;
	return $current_max
	}
}



sub print_delete_tissue_form {
    print "<center>\n";

    print "Are you sure you want to delete the tissue record $input{bnhm_id}.$input{tissue_num}?\n";

    print "<form name=parentform action=/cgi/biocode_add_tissue method=post>\n";
    print "<input type=hidden name=mode value=delete>\n";
    print "<input type=hidden name=special value=final>\n";
    print "<input type=hidden name=bnhm_id value=\"$input{bnhm_id}\">\n";
    print "<input type=hidden name=tissue_num value=\"$input{tissue_num}\">\n";
    print "<input type=hidden name=entry_by value=\"$input{entry_by}\">\n";
    print "<input type=submit value=\"Delete Tissue Record\">\n";
    print "</form>\n";
    print "</center>\n";
}

sub delete_tissue_record {

    # save record first
    $save = "insert into biocode_tissue_deleted select * from biocode_tissue where bnhm_id = '$input{bnhm_id}' and tissue_num = $input{tissue_num}";
    &process_query($save, "biocode");
    
    $delete = "delete from biocode_tissue where bnhm_id = '$input{bnhm_id}' and tissue_num = $input{tissue_num}";
    # print "delete: $delete<p>";
    &process_query($delete, "biocode");

    ## need to update biocode?
    ($current_max) = &get_one_record("select max(tissue_num) from biocode_tissue where bnhm_id = '$input{bnhm_id}'","biocode");
    if (!$current_max) {
	$upd = "update biocode set Tissue =null where bnhm_id = '$input{bnhm_id}'";
	&process_query($upd, "biocode");
    } elsif ($current_max < $input{tissue_num}) {
	$upd = "update biocode set Tissue = $current_max where bnhm_id = '$input{bnhm_id}'";
	&process_query($upd, "biocode");
    }

}

sub print_delete_tissue_form_done {
    $input{bnhm_id} = uc($input{bnhm_id});
    print "<center>\n";
    print "Tissue record $input{bnhm_id}.$input{tissue_num} has been deleted.\n";
    print "</center>\n";
}
