#!/usr/bin/perl

print "Content-type: text/html\n\n";

print <<END;

<html>
<head>
<title>


Moorea Biocode Collections
</title>

<style type="text/css">

p, td, body {font-family: arial, verdana, helvetica, sans-serif;}
p, td, body {font-size: 10px;}
a.nounderline {
        text-decoration: none;  /* this removes underlining */
        color:  white;
        outline: none;
        }
select {
        font-family: arial, verdana, helvetica, sans-serif;
        font-size: 8pt;
        }
input {  
        font-family: arial, verdana, helvetica, sans-serif;
        font-size: 8pt;
      }
td.headertype {
        font-size: 12px; 
/*        font-weight: bold; */
        background-color: #cccccc;
        }


</style>

<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">

</head>

<body bgcolor=white>

<!-- blue color=669ACC  gray color=gray -->

<center>
  <table cellpadding=0 cellspacing=0 border=0 width="90%">
    <tr>
      <td bgcolor=#669ACC width=5%></td>
      <td bgcolor=#FFFFFF valign=top>
      <table cellpadding=5 border=0>
        <tr>
          <td>

<table>
<tr>
<td>
<img src=/images/biocode_new.jpg height=70>
</td>
<td>
<big><big><big>
Moorea Biocode Collections - Label Printing
</td>
</tr>
</table>

          </td>
        </tr>
       </table>
      </td>
    </tr>
    <tr bgcolor="gray"> 
      <td width=100% colspan="2" valign=center>&nbsp;

      </td>

    </tr>
    <tr> 
      <td bgcolor=#669ACC valign=top width=5%>&nbsp;


       <!-- insert side bar links here -->
</td>

      <td valign=top>

<!-- start of body --->



<center>
<small>
<i>
Back to: <a href=/>Moorea Biocode Collections</a>
</small>
</i>

<p>

<form action=/cgi/biocode_label method=post>
<input type=hidden name=labeltype value=locality_collector_ecology>

<table border=0 width=90%>

<tr>
<td>


<p>

<table border cellpadding=8 width=100%>

<tr>
<td colspan=4 align=center class=headertype>
<b>Locality, Collector, and Ecology Labels</b>
</td>
</tr>

<tr>

<td>
<br>
</td>
<td align=center>
Type of label
</td>

<td align=center>
How many labels
</td>
<td rowspan=4 align=center>

<table>
<tr>
<td align=right>
Date format?
</td>

<td>
<select name="dateformat" size="1">
<option selected>2006apr14</option>
<option>14.iv.2006</option>
</select>
</td>
</tr>

<tr>
<td align=right>
Lat/long format?
</td>
<td>
<select name="latlongformat" size="1">
<option selected>decimal</option>

<option>deg min sec</option>
</select>
</td>
</tr>


<tr>
<td align=right>
Font size?
</td>
<td>
<select name="fontsize" size="1">
<option>4</option>
<option selected>5</option>

<option>6</option>
<option>7</option>
<option>8</option>
<option>9</option>
<option>10</option>
<option>11</option>
<option>12</option>
<option>14</option>
<option>16</option>

<option>18</option>
<option>24</option>
</select>
</td>
</tr>


<tr>
<td align=right>
Number of columns?
</td>
<td>
<select name="numcolumns" size="1">
<option>1</option>

<option>2</option>
<option>3</option>
<option>4</option>
<option selected>5</option>
<option>6</option>
<option>7</option>
<option>8</option>
<option>9</option>
<option>10</option>

<option>11</option>
<option>12</option>
<option>13</option>
<option>14</option>
<option>15</option>
<option>16</option>
<option>17</option>
<option>18</option>
<option>19</option>

<option>20</option>
</select>
</td>
</tr>


<tr>
<td align=right>
Lines around labels?
</td>
<td>
<select name="lines" size="1">
<option selected>no</option>
<option>yes</option>

</select>
</td>
</tr>

<tr>
<td colspan=2 align=center>
&nbsp;<br>
<input type="submit" value="Submit">
<input type="reset" value="Reset">
</td>
</tr>
</table>

</td>
</tr>

<tr>

<td align=center rowspan=3>
<input type=text size=10 name=EventID>
<br>
Collecting Event<br>Number<br>
</td>

<td align=right>
locality
</td>
<td>
<input type=text size=5 name=num_locality_labels>
</td>



</tr>

<tr>
<td align=right>
collector
</td>
<td>
<input type=text size=5 name=num_collector_labels>
</td>
</tr>

<tr>
<td align=right>
ecology
</td>
<td>
<input type=text size=5 name=num_ecology_labels>

</td>
</tr>

</table>

</form>

<p>


<form action=/cgi/biocode_label method=post>
<input type=hidden name=labeltype value=identification>

<table border cellpadding=8 width=100%>

<tr>
<td colspan=4 align=center class=headertype>

<b>Identification Labels</b>
</td>
</tr>

<tr>
<td nowrap>
range of specimen numbers 
<br>
from
<input type=text size=6 name=spec_num_low>
to
<input type=text size=6 name=spec_num_high> 
</td>

<td>
institutional code

<select name=institution_code size=1>
<option>AMNH
<option>ANIC
<option>BPBM
<option selected>EMEC
<option>INHS
<option>MCZ
<option>MIZA
<option>SCC
<option>SDS
<option>USNM
</select>
</td>

<td align=center rowspan=3>

<table>

<tr>
<td align=right>
Font size?
</td>
<td>
<select name="fontsize" size="1">
<option>4</option>
<option selected>5</option>
<option>6</option>
<option>7</option>
<option>8</option>
<option>9</option>

<option>10</option>
<option>11</option>
<option>12</option>
<option>14</option>
<option>16</option>
<option>18</option>
<option>24</option>
</select>
</td>
</tr>


<tr>
<td align=right>
Number of columns?
</td>
<td>
<select name="numcolumns" size="1">
<option>1</option>
<option>2</option>
<option>3</option>
<option>4</option>
<option selected>5</option>

<option>6</option>
<option>7</option>
<option>8</option>
<option>9</option>
<option>10</option>
<option>11</option>
<option>12</option>
<option>13</option>
<option>14</option>

<option>15</option>
<option>16</option>
<option>17</option>
<option>18</option>
<option>19</option>
<option>20</option>
</select>
</td>
</tr>


<tr>
<td align=right>
Lines around labels?
</td>
<td>
<select name="lines" size="1">
<option selected>no</option>
<option>yes</option>
</select>
</td>
</tr>

<tr>
<td colspan=2 align=center>
<input type="submit" value="Submit">

<input type="reset" value="Reset">
</td>
</tr>
</table>

</td>

</tr>

</table>

</form>

<form action=/cgi/biocode_label method=post>
<input type=hidden name=labeltype value=specimen_num>

<p>

<table border cellpadding=8 width=100%>

<tr>
<td colspan=4 align=center class=headertype>
<b>Specimen Number Labels</b>
</td>
</tr>

<tr>
<td nowrap>
range of specimen numbers 
<br>
from
<input type=text size=6 name=spec_num_low> 
to

<input type=text size=6 name=spec_num_high> 
</td>
<td>
institutional code
<select name=institution_code size=1>
<option>AMNH
<option>ANIC
<option>BPBM
<option selected>EMEC
<option>INHS
<option>MCZ
<option>MIZA
<option>SCC
<option>SDS
<option>USNM
</select>

<p>

institutional name for label
<select name=institution_for_label size=1>
<option selected>Univ. of California
</select>

</td>

<td align=center rowspan=3>

<table>
<tr>
<td align=right>
Font size?
</td>
<td>

<select name="fontsize" size="1">
<option>4</option>
<option selected>5</option>
<option>6</option>
<option>7</option>
<option>8</option>
<option>9</option>
<option>10</option>
<option>11</option>

<option>12</option>
<option>14</option>
<option>16</option>
<option>18</option>
<option>24</option>
</select>
</td>
</tr>


<tr>
<td align=right>

Number of columns?
</td>
<td>
<select name="numcolumns" size="1">
<option>1</option>
<option>2</option>
<option>3</option>
<option>4</option>
<option selected>5</option>
<option>6</option>
<option>7</option>

<option>8</option>
<option>9</option>
<option>10</option>
<option>11</option>
<option>12</option>
<option>13</option>
<option>14</option>
<option>15</option>
<option>16</option>

<option>17</option>
<option>18</option>
<option>19</option>
<option>20</option>
</select>
</td>
</tr>


<tr>
<td align=right>
Lines around labels?
</td>

<td>
<select name="lines" size="1">
<option selected>no</option>
<option>yes</option>
</select>
</td>
</tr>


<tr>
<td align=center colspan=2>
<input type="submit" value="Submit">
<input type="reset" value="Reset">
</td>
</tr>

</table>

</td>

</tr>
</table>

</form>

</td>
</tr>
</table>



<!-- end of body --->

      </td>
    </tr>

    <tr bgcolor="#669ACC"> 
      <td colspan=2 align=center>&nbsp;</td>
    </tr>
    <tr> 
      <td colspan=2 align=center> 
      <a href="/">Moorea Biocode</a></td>
    </tr>

    <tr> 
      <td colspan="2" align="center"> &nbsp;<br>
      </td>
    </tr>
  </table>
</center>

</body></html>



END
