#!/bin/sh
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0104-0105
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0120
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0130
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0134-0135
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0140
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0142
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0144
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0146
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0148
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0166-0170
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0171-0178
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0193_0267
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0268-0370
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0371
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0372-0419
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0420
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0421-0476
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0477-0486
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0491
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_0583-0602
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1001
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1002
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1003
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1004
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1005
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1006-1007
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1008
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1009
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1010
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1011
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1012
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1013
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1014
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1015
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1016
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1017
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1018
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1019
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1020
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1021
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1022-1043
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1044
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1067
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1068
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1071-1072
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1074
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1077
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1080
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1081
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1139-1140
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1141
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1165-1193
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1194-1197
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1204-1207
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1208_1239
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1211
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1240-1243
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1245-1305
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1306-1311
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1314-1321
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1323-1325
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1327-1344
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1345-1352
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1353-1358
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1360-1362
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1364-1366
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1368-1370
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1372
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1373-1383
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1387-1402
/usr/bin/perl resize.pl /data3/biocode/photos/ID_folders/XMOO_1572-1574
