<p>
<center>
<b>Catalog ID Number
</b>
</center>
<hr>
The Catalog ID Number is a unique identifier for the specimen
record.  It is composed of two parts: 
<li>an Institutional Code, usally "MBIO" 
<li>the next available integer for that  Institutional Code
<p>

Other institutional codes may appear here if the specimen was databased
on behalf of another institution.  
<p>
Please contact the database manager to add a new
institution to this list.
<p>

<p>Max size = 4 characters for the Institutional Code followed by an integer
