<p>
<center>
<b>Collector
</b>
</center>
<hr>
The name of the person/people who collected the specimen.  Enter up to eight
names in the order they should appear on the record. If there are
more than eight collectors, put additional names in the Notes/Remarks field.
<p>
To add a name that is not on the list, click on [<i>new</i>] next to one
of the Collector menus, fill out
the form that pops up, and click Submit.  Once the
new name has been succesfully loaded, 
click on "Put new name on form" 
and the name will appear in the appropriate box on the data entry form.
<p>
Max - 128 characters
