<p>
<center>
<b>Collector's Field Numbers
</b>
</center>
<hr>
Any personal identification numbers the collector assigned
while in the field and/or wrote on the specimen's labels.  These numbers usually
correspond to notations in the collector's field notebook.
<ul>
<li><b>loc</b>&nbsp;&nbsp; collector's code for the locality  (max 50 chars)
<li><b>indiv</b>&nbsp;&nbsp; collector's code for the individual specimen (max 50 chars)
<li><b>misc</b>&nbsp;&nbsp; any other number the collector used (max 35 chars)
</ul>
<p>
