<p>
<center>
<b>Date Collected or Date Taken
</b>
</center>
<hr>
<i>Specimens</i>: the year, month and day the specimen was collected
<br>
<i>Tissue Samples</i>: the year, month and day the tissue sample was taken
<br>
<i>Photos</i>: the year, month and day the photo was taken
<p>
<ul>
<li><b>Year</b> 4 digits
<li><b>Month</b> 2 digits 01-12 
<li><b>Day</b> 2 digits 01-31
</ul>
<p>

If the collection date is a <b>range</b>, such as "March 3-5, 1928", put
the beginning of the range in Coll Date and the end of the range in Coll Date 2.

<p>
