<p>
<center>
<b>Depth in Meters
</b>
</center>
<hr>
The depth, in meters, at which this Collecting Event was made.
<p>
If the exact depth is known, enter it in the first box.
<p>
If the depth is a <b>range</b>, such as "2-3 meters", enter
the beginning of the range ("2") in the first box and the end of the range ("3") in the second box.

<p>
meters = feet * 0.3048
<p>
type = numeric with 4 decimal places


