<p>
<center>
<b>Elevation in Meters
</b>
</center>
<hr>
The elevation, in meters, at which the specimen was collected.
<p>
If the exact elevation is known, enter it in the first box.
<p>
If the elevation is a <b>range</b>, such as "2000-3000 meters", enter
the beginning of the range ("2000") in the first box and the end of the range ("3000") in the second box.
<p>
meters = feet * 0.3048
<p>
type = numeric with 4 decimal places


