<p>
<center>
<b>Institution
</b>
</center>
<hr>
The full name of the institution or individual that "owns" this specimen. 
For specimens that are owned by one institution
but physically housed at a different institution, 
enter the owner in the Institution field, and add a note to the Notes field.
See
<a href=/biocode/Institutions.html target=list>List of Institutions</a>

<p>
examples: 
 <li><i>Bishop Museum</i>
 <li><i>Planes's Lab</i>

<p>
max: 255 characters


