<p>
<center>
<b>Institution Code</b>
</center>
<hr>
This is a 4-letter code that identifies the 
collection. Default is "EMEC" for Essig Museum of
Entomology.  
Other institutional codes may appear here if the specimen was databased
on behalf of another institution.  See 
<a href=http://hbs.bishopmuseum.org/codens/codens-inst.html target=list>this list</a>
of other institution codes.

<p>
The Institution Code is prepended to the Catalog Number
to create a unique
collection number for the specimen.

<p>

<p>Max size = 4 characters
