<p>
<center>
<b>Parent Record
</b>
</center>
<hr>
The Parent Record is the
 catalog ID number from which this one was created or "cloned".
Usually the parent record included a number of individuals, which 
were later catalogued separately.
<br>
example: <i>MBIO41107</i>
<br>
max: 24 characters
<p>
The Child Record field only appears if this record has one or more
"children" in the database, i.e., new records that were cloned from this record.
