<p>
<center>
<b>Related Catalog Item
</b>
</center>
<hr>
Number for an item that was collected with or is associated with the specimen. 
<p>
For example, if a predator is collected with prey, that prey would be a related catalog item, particularly if mounted separately. Similarly, if a parasite were reared from a host and the host remains are maintained in a different area or mounted on a different medium, then each other's catalog number would be placed in that field to indicate linkage.

<p>
example: <i>host plant #7750</i>


<p>
max: 128 characters
