<p>
<center>
<b>Time of Day
</b>
</center>
<hr>
The time of the day the specimen was collected.
<p>
This field is flexible.  Examples: "4pm" or "early morning" or "0930 PST".  The
Moorea Biocode project typically uses European-style time formats such as
"1600" and "0600.
<p>
If the time is a  <b>range</b>, such as 9:00-9:30am, put
the beginning of the range in Time of Day and the end of the range in Time of Day 2.
<p>
max = 128 characters
