<p>
<center>
<b>Degrees/Minutes/Seconds Lat/Lon
</b>
</center>
<hr>
The latitude and longitude in Degrees/Minutes/Seconds format.
<p>
Examples of acceptable formats:
<ul>
<li>16&#176; 27' 00 S
<li>156&#176; 23' 29'' W 
<li>04 0 0 N
<li>34 12 27.6 N
<li>36° 54.947' S
<li>071 27.417 W
</ul>
<p>
For deg/min/sec:
<br>
Four fields, each separated by one space. No minus signs, no alpha characters. 3rd field can be a decimal number. 4th field must be E,W,N, or S.
<br>
For deg/dec min:
<br>
Three fields, each separated by one space. No minus signs, no alpha characters. 3rd field must be E,W,N, or S.



<p>
<b>Automatic conversion to decimal</b> &nbsp;
This Lat/Lon will be automatically converted to decimal lat/longs
 when the record is submitted.

<p>
max = 255 characters


